// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmLXIXF8Pz3Ns9yOVl52KkgxsPhjvgALE',
    appId: '1:606480576114:web:6cf1911e1a8a374f819ceb',
    messagingSenderId: '606480576114',
    projectId: 'brava-academy',
    authDomain: 'brava-academy.firebaseapp.com',
    storageBucket: 'brava-academy.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0_Ojy8JKBem1KXHGeWPwCGWKoXW3xL6k',
    appId: '1:606480576114:android:d451434f4dbadcde819ceb',
    messagingSenderId: '606480576114',
    projectId: 'brava-academy',
    storageBucket: 'brava-academy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY6t0R2IHewQ2V6O7A_SN54107ajhjSjk',
    appId: '1:606480576114:ios:2ca6d30a77dfcdb8819ceb',
    messagingSenderId: '606480576114',
    projectId: 'brava-academy',
    storageBucket: 'brava-academy.appspot.com',
    iosBundleId: 'com.example.brava',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY6t0R2IHewQ2V6O7A_SN54107ajhjSjk',
    appId: '1:606480576114:ios:378a60313a6e5e2a819ceb',
    messagingSenderId: '606480576114',
    projectId: 'brava-academy',
    storageBucket: 'brava-academy.appspot.com',
    iosBundleId: 'com.example.brava.RunnerTests',
  );
}
